# Generated by Django 3.2 on 2021-05-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card_login_app', '0002_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Correct Addition'),
        ),
        migrations.AddField(
            model_name='user',
            name='capital_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Correct State capitals'),
        ),
        migrations.AddField(
            model_name='user',
            name='div_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Correct Dvision'),
        ),
        migrations.AddField(
            model_name='user',
            name='flag_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Correct State flags'),
        ),
        migrations.AddField(
            model_name='user',
            name='multi_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Correct Multiplication'),
        ),
        migrations.AddField(
            model_name='user',
            name='shape_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Correct State shapes'),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Correct Subtraction'),
        ),
    ]
