# Generated by Django 3.2 on 2021-05-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card_login_app', '0003_auto_20210523_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='username',
        ),
    ]
