# Generated by Django 3.2 on 2021-05-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card_login_app', '0004_rename_user_id_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Correct Addition'),
        ),
    ]
