# Generated by Django 3.2 on 2021-05-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card_login_app', '0005_alter_user_add_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='capital_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Correct State capitals'),
        ),
        migrations.AlterField(
            model_name='user',
            name='div_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Correct Dvision'),
        ),
        migrations.AlterField(
            model_name='user',
            name='flag_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Correct State flags'),
        ),
        migrations.AlterField(
            model_name='user',
            name='multi_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Correct Multiplication'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shape_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Correct State shapes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Correct Subtraction'),
        ),
    ]
