# Generated by Django 3.2 on 2021-05-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card_login_app', '0007_auto_20210524_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='word_scram_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Correct Word Scrambler'),
        ),
    ]
