# Generated by Django 3.2 on 2021-05-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
