# Generated by Django 3.2 on 2021-05-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card_app', '0003_auto_20210521_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entry Date'),
        ),
        migrations.AddField(
            model_name='state',
            name='order_statehood',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Order of Statehood'),
        ),
    ]
