# Generated by Django 3.2 on 2021-05-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card_app', '0005_alter_state_date_of_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
