# Generated by Django 3.2 on 2021-05-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card_app', '0009_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='list',
            name='idea_date',
            field=models.DateField(blank=True, null=True, verbose_name='Born Date'),
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Priority Number'),
        ),
    ]
